### ISSUE TITLE
[Bug] Create or update issue

### ISSUE THREAD

**Issue by TomKovac** [ix-ax/axopen.templates#5]
CreateOrUpdate method does not create the data item but its IsDone() method returns 'TRUE'. 

How to replicate:
https://github.com/ix-ax/AXOpen/tree/fw4_template_alignment
https://github.com/ix-ax/axopen.templates/tree/CreateOrUpdateIssue

Starter unit stucks in AutomatSequence at Step[99] (UPDATE ITEM:  + timestamp) as it did not create an the data item at  
Step[2] (CREATE ITEM:  + timestamp)

**Comment by PTKu** [comment]
@TomKovac can we close this?
Addressed here https://github.com/ix-ax/AXOpen/commit/23e6aa4d3cc47f0a159099e3cabe69dd29ba99f7

**Comment by TomKovac** [comment]
@PTKu the bug was on the axopen side, so I am closing this issue.
